/*
 * This source file was generated by the Gradle 'init' task
 */
package org.task_1_2;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test
    // void appGetSummTest(){

    //     Dealer dealer = new Dealer();
    //     dealer.gameSituation()
    //     }
    // void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }

}
