/*
 * This source file was generated by the Gradle 'init' task
 */
package org.Task_1_1_4;

public class GraphDemo {
    public static void main(String[] args) {
        String filename = "graph.txt";

        // Граф с матрицей смежности
        AdjacencyMatrixGraph adjacencyMatrixGraph = new AdjacencyMatrixGraph(5);
        // adjacencyMatrixGraph.readFile(filename);
        System.out.println("Изначальная матрица смежности:");
        adjacencyMatrixGraph.printGraph();

        // Добавление вершины
        System.out.println("Добавление вершины 5:");
        adjacencyMatrixGraph.addVertex(5);
        adjacencyMatrixGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (4, 5):");
        adjacencyMatrixGraph.addEdge(4, 5);
        adjacencyMatrixGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (4, 5):");
        adjacencyMatrixGraph.removeEdge(4, 5);
        adjacencyMatrixGraph.printGraph();

        // Удаление вершины
        System.out.println("Удаление вершины 5:");
        adjacencyMatrixGraph.removeVertex(5);
        adjacencyMatrixGraph.printGraph();

        // Граф со списком смежности
        AdjacencyListGraph adjacencyListGraph = new AdjacencyListGraph();
        // adjacencyListGraph.readFile(filename);
        System.out.println("\nИзначальный список смежности:");
        adjacencyListGraph.printGraph();

        // Добавление вершины
        System.out.println("Добавление вершины 5:");
        adjacencyListGraph.addVertex(5);
        adjacencyListGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (4, 5):");
        adjacencyListGraph.addEdge(4, 5);
        adjacencyListGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (4, 5):");
        adjacencyListGraph.removeEdge(4, 5);
        adjacencyListGraph.printGraph();

        // Удаление вершины
        System.out.println("Удаление вершины 5:");
        adjacencyListGraph.removeVertex(5);
        adjacencyListGraph.printGraph();

        // Граф с матрицей инцидентности
        IncidenceMatrixGraph incidenceMatrixGraph = new IncidenceMatrixGraph(5);
        // incidenceMatrixGraph.readFile(filename);
        System.out.println("\nИзначальная матрица инцидентности:");
        incidenceMatrixGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (0, 1):");
        incidenceMatrixGraph.addEdge(0, 1);
        incidenceMatrixGraph.printGraph();

        System.out.println("Добавление ребра (1, 2):");
        incidenceMatrixGraph.addEdge(1, 2);
        incidenceMatrixGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (0, 1):");
        incidenceMatrixGraph.removeEdge(0, 1);
        incidenceMatrixGraph.printGraph();
    }
}
