/*
 * This source file was generated by the Gradle 'init' task
 */
package org.Task_1_1_4;

public class GraphDemo {
    public static void main(String[] args) {
        String filename1 = "/home/aly0na/OOP/OOP/Task_1_1_4/app/src/main/java/org/Task_1_1_4/graph1.txt";
        String filename2 = "/home/aly0na/OOP/OOP/Task_1_1_4/app/src/main/java/org/Task_1_1_4/graph2.txt";
        // Граф с матрицей смежности
        AdjacencyMatrixGraph adjacencyMatrixGraph = new AdjacencyMatrixGraph(5);
        adjacencyMatrixGraph.readFile(filename1);
        System.out.println("Изначальная матрица смежности:");
        adjacencyMatrixGraph.printGraph();

        // Добавление вершины
        System.out.println("Добавление вершины 6:");
        adjacencyMatrixGraph.addVertex(6);
        adjacencyMatrixGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (5, 6):");
        adjacencyMatrixGraph.addEdge(5, 6);
        adjacencyMatrixGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (5, 6):");
        adjacencyMatrixGraph.removeEdge(5, 6);
        adjacencyMatrixGraph.printGraph();

        // Удаление вершины
        System.out.println("Удаление вершины 5:");
        adjacencyMatrixGraph.removeVertex(5);
        adjacencyMatrixGraph.printGraph();

        // Граф со списком смежности
        AdjacencyListGraph adjacencyListGraph = new AdjacencyListGraph();
        adjacencyListGraph.readFile(filename2);
        System.out.println("\nИзначальный список смежности:");
        adjacencyListGraph.printGraph();

        // Добавление вершины
        System.out.println("Добавление вершины 5:");
        adjacencyListGraph.addVertex(5);
        adjacencyListGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (4, 5):");
        adjacencyListGraph.addEdge(4, 5);
        adjacencyListGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (4, 5):");
        adjacencyListGraph.removeEdge(4, 5);
        adjacencyListGraph.printGraph();

        // Удаление вершины
        System.out.println("Удаление вершины 5:");
        adjacencyListGraph.removeVertex(5);
        adjacencyListGraph.printGraph();

        // Граф с матрицей инцидентности
        IncidenceMatrixGraph incidenceMatrixGraph = new IncidenceMatrixGraph(6);
        incidenceMatrixGraph.readFile(filename1);
        System.out.println("\nИзначальная матрица инцидентности:");
        incidenceMatrixGraph.printGraph();

        // Добавление рёбер
        System.out.println("Добавление ребра (0, 1):");
        incidenceMatrixGraph.addEdge(0, 1);
        incidenceMatrixGraph.printGraph();

        System.out.println("Добавление ребра (1, 2):");
        incidenceMatrixGraph.addEdge(1, 2);
        incidenceMatrixGraph.printGraph();

        // Удаление рёбер
        System.out.println("Удаление ребра (0, 1):");
        incidenceMatrixGraph.removeEdge(0, 1);
        incidenceMatrixGraph.printGraph();
    }
}
