/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    java
    jacoco
    id("com.diffplug.spotless") version "7.0.0.BETA2"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.task_1.HeapSort"
}


tasks.jacocoTestReport {
    val reportDir = file("../build/reports/jacoco/test")
    reports.xml.outputLocation = reportDir.resolve("jacocoTestReport.xml")
    reports {
        xml.required = true
    }

}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
    finalizedBy(tasks.javadoc)
}


tasks.javadoc {
    destinationDir = file("../build/docs/javadoc")
}

spotless {
    java {
        googleJavaFormat().aosp().reflowLongStrings().formatJavadoc(true).reorderImports(true)
    }
}
